import type { FeedTrack, PublicCreatorProfile } from "./types";

export const MOCK_FEED_TRACKS: FeedTrack[] = [
  {
    id: "t1",
    title: "Midnight Drive",
    creatorId: "c1",
    creatorName: "Nova Beats",
    creatorSlug: "nova-beats",
    micTier: "gold",
    plays: 12400,
    weightedRating: 4.9,
    totalRatings: 312,
    likes: 89,
    commentsCount: 24,
    saved: false,
    engagementIndicator: "High engagement",
    audioPreviewUrl: null,
  },
  {
    id: "t2",
    title: "Neon Pulse",
    creatorId: "c2",
    creatorName: "Luna Drift",
    creatorSlug: "luna-drift",
    micTier: "silver",
    plays: 8200,
    weightedRating: 4.7,
    totalRatings: 156,
    likes: 42,
    commentsCount: 12,
    saved: false,
    engagementIndicator: "Rising",
    audioPreviewUrl: null,
  },
  {
    id: "t3",
    title: "Skyline",
    creatorId: "c3",
    creatorName: "Echo Wave",
    creatorSlug: "echo-wave",
    micTier: "gold",
    plays: 24100,
    weightedRating: 5.0,
    totalRatings: 501,
    likes: 120,
    commentsCount: 38,
    saved: true,
    engagementIndicator: "Top performer",
    audioPreviewUrl: null,
  },
];

export const MOCK_PUBLIC_CREATORS: Record<string, PublicCreatorProfile> = {
  "nova-beats": {
    id: "c1",
    username: "Nova Beats",
    slug: "nova-beats",
    profileImageUrl: null,
    bannerImageUrl: null,
    bio: "Producer. Beats and vibes.",
    followers: 1200,
    following: 89,
    totalPlays: 45000,
    weightedRating: 4.8,
    micTier: "gold",
    creatorLevel: 24,
    reputationSummary: "Verified Creator",
    pinnedTrackIds: ["t1"],
    featuredCollabsPlaceholder: true,
  },
  "luna-drift": {
    id: "c2",
    username: "Luna Drift",
    slug: "luna-drift",
    profileImageUrl: null,
    bannerImageUrl: null,
    bio: "Lo-fi and chill.",
    followers: 420,
    following: 56,
    totalPlays: 18000,
    weightedRating: 4.6,
    micTier: "silver",
    creatorLevel: 14,
    reputationSummary: "Rising Creator",
    pinnedTrackIds: ["t2"],
    featuredCollabsPlaceholder: false,
  },
  "echo-wave": {
    id: "c3",
    username: "Echo Wave",
    slug: "echo-wave",
    profileImageUrl: null,
    bannerImageUrl: null,
    bio: "Electronic producer.",
    followers: 2100,
    following: 120,
    totalPlays: 72000,
    weightedRating: 4.9,
    micTier: "gold",
    creatorLevel: 30,
    reputationSummary: "Top Creator",
    pinnedTrackIds: ["t3"],
    featuredCollabsPlaceholder: true,
  },
};
