import type { Metadata } from "next";
import Link from "next/link";
import Navbar from "../components/Navbar";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "";
const privacyUrl = `${siteUrl.replace(/\/$/, "")}/privacy`;

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy for SupremeBeats Studio — how we collect, use, and protect your information.",
  alternates: { canonical: privacyUrl },
  openGraph: {
    title: "Privacy Policy | SupremeBeats Studio",
    description: "Privacy Policy for SupremeBeats Studio — how we collect, use, and protect your information.",
    url: privacyUrl,
    siteName: "SupremeBeats Studio",
    type: "website",
    locale: "en_US",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[var(--background)]">
      <Navbar />
      <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
        <h1 className="text-3xl font-bold text-white">Privacy Policy</h1>
        <p className="mt-2 text-sm text-[var(--muted)]">
          Last updated: {new Date().toISOString().slice(0, 10)}
        </p>

        <div className="mt-10 space-y-8 text-sm text-[var(--muted)]">
          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">1. Who we are</h2>
            <p>
              SupremeBeats Studio (“we,” “our,” or “us”) operates the website and service at{" "}
              <a href={siteUrl} className="text-[var(--neon-green)] hover:underline">
                {siteUrl.replace(/^https?:\/\//, "")}
              </a>
              . We are an AI-powered music creator platform and social network. This Privacy Policy explains how we collect, use, and protect your information when you use our service.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">2. Information we collect</h2>
            <p className="mb-2">We collect information you provide and data generated by your use of the service:</p>
            <ul className="list-inside list-disc space-y-1 pl-2">
              <li><strong className="text-white">Account data:</strong> email address, password (hashed), username/display name, and optional profile information (bio, profile picture, cover image) when you register or update your profile.</li>
              <li><strong className="text-white">Sign-in with third parties:</strong> if you sign in with Google or Facebook, we receive basic profile information (e.g. email, name) as permitted by those providers.</li>
              <li><strong className="text-white">Payment data:</strong> payment and subscription flows are handled by Stripe. We do not store your full card number; we store billing-related identifiers and subscription status as needed to provide the service.</li>
              <li><strong className="text-white">Usage and content:</strong> projects, generated assets (beats, tracks, artwork), comments, likes, and other activity you perform on the platform.</li>
              <li><strong className="text-white">Technical data:</strong> IP address, browser type, device information, and log data (e.g. access times) to operate and secure the service.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">3. How we use your information</h2>
            <p>We use the information we collect to:</p>
            <ul className="mt-2 list-inside list-disc space-y-1 pl-2">
              <li>Create and manage your account, authenticate you, and provide the SupremeBeats service.</li>
              <li>Display your public profile (e.g. username, profile picture, creations) to other users as part of the creator network and discovery features.</li>
              <li>Process payments, manage subscriptions and credits, and prevent fraud.</li>
              <li>Send you service-related messages (e.g. account confirmation, password reset, important product updates).</li>
              <li>Improve the service, fix issues, and analyze usage in an aggregated or anonymized way.</li>
              <li>Comply with law and enforce our terms and policies.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">4. Sharing and disclosure</h2>
            <p>
              We do not sell your personal information. We may share data with: (a) service providers who help us operate the platform (e.g. hosting, auth, payments, analytics), under strict confidentiality and data-processing terms; (b) other users as needed for the service (e.g. your public profile and content); (c) law enforcement or other parties when required by law or to protect rights and safety.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">5. Data retention and security</h2>
            <p>
              We retain your information for as long as your account is active or as needed to provide the service, resolve disputes, and comply with legal obligations. We use industry-standard measures (including encryption and access controls) to protect your data. No method of transmission or storage is 100% secure; we encourage strong passwords and secure use of your account.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">6. Your choices and rights</h2>
            <p className="mb-2">You can:</p>
            <ul className="list-inside list-disc space-y-1 pl-2">
              <li>Update or delete profile information (e.g. username, bio, images) in your account settings.</li>
              <li>Request access to, correction of, or deletion of your personal data by contacting us.</li>
              <li>Opt out of non-essential emails (e.g. marketing) where we offer that option.</li>
              <li>Disconnect third-party sign-in (Google/Facebook) from your account where the product allows.</li>
            </ul>
            <p className="mt-2">
              If you are in the European Economic Area, UK, or another jurisdiction with similar laws, you may have additional rights (e.g. data portability, restriction of processing, right to object). Contact us to exercise them.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">7. Cookies and similar technologies</h2>
            <p>
              We use cookies and similar technologies to keep you signed in, remember preferences, and operate the service securely. You can control cookies through your browser settings; some features may not work correctly if you disable them.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">8. Children</h2>
            <p>
              Our service is not directed at children under 13 (or the applicable age in your country). We do not knowingly collect personal information from children. If you believe we have collected such data, please contact us so we can delete it.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">9. International transfers</h2>
            <p>
              Your data may be processed in the United States or other countries where our service providers operate. We ensure appropriate safeguards (e.g. standard contractual clauses or equivalent) where required by law for such transfers.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">10. Changes to this policy</h2>
            <p>
              We may update this Privacy Policy from time to time. We will post the revised policy on this page and update the “Last updated” date. Continued use of the service after changes constitutes acceptance of the updated policy. For material changes, we may provide additional notice (e.g. email or in-product).
            </p>
          </section>

          <section id="data-deletion">
            <h2 className="mb-2 text-lg font-semibold text-white">11. Data deletion requests</h2>
            <p>
              If you signed in with Facebook and requested data deletion through Facebook’s settings (Settings &amp; Privacy → Settings → Apps and Websites), we receive that request and process it. We delete or anonymize your account and associated data. You may receive a confirmation code; you can use the link we provide to check the status of your request. For other sign-in methods or to request deletion directly, contact us (see Contact below).
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-white">12. Contact</h2>
            <p>
              For privacy-related questions, requests, or complaints, contact us at the support or contact information provided on our website (e.g. contact form or support email). We will respond in accordance with applicable law.
            </p>
          </section>
        </div>

        <div className="mt-12 flex flex-wrap gap-4">
          <Link
            href="/"
            className="rounded-lg border border-white/20 bg-white/5 px-4 py-2 text-sm font-medium text-white hover:bg-white/10"
          >
            Back to home
          </Link>
          <Link
            href="/login"
            className="rounded-lg bg-[var(--neon-green)] px-4 py-2 text-sm font-semibold text-black hover:bg-[var(--neon-green-dim)]"
          >
            Log in
          </Link>
        </div>
      </main>
    </div>
  );
}
